### ISSUE TITLE
Permission issue when running grunt in docker container for the first time

### ISSUE THREAD

**Issue by natenolting** [paulbunyannet/bash#3]
https://github.com/paulbunyannet/bash/blob/8d9702d4dddf0da444a16018527108532462b253/docker/dock.sh#L556

@castillo-n It looks like yarn needs rights to create `/var/www/.cache` in the code container but docker use doesn't have write access above `/var/www/html`. 

```
⇒  docker-compose exec -T code yarn global add grunt-cli && yarn add grunt --dev && grunt
WARNING: The USER_ID variable is not set. Defaulting to a blank string.
WARNING: The XDEBUG_CONFIG variable is not set. Defaulting to a blank string.
/usr/share/yarn/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/var/www/.cache'
    at Object.fs.mkdirSync (fs.js:895:18)
    at sync (/usr/share/yarn/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/share/yarn/node_modules/mkdirp/index.js:77:24)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:31:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

Trying to set the `cache-folder` to a cache folder in the code like `docker-compose exec -T code yarn config set cache-folder /var/www/html/cache` gives the same error.

**Comment by silentdragonz** [comment]
Grunt should already be installed when the image is made so it doesn't need to be installed at any other time. Also to run the locally installed version of grunt for the project you just do `yarn run grunt`

**Comment by natenolting** [comment]
I fixed it https://github.com/paulbunyannet/bash/blob/master/docker/dock.sh#L553
